[theme]
primaryColor = "#37474f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
